### ISSUE TITLE
Koch TC30 Integration

### ISSUE THREAD

**Issue by calibanorg** [peteh/doorman#19]
### New Thread für die TC30 Integration von Koch

**Ziel:**
- Test ob Doorman mit TC30 funktioniert Out of the box

Folgendes wurde bereits geklärt in Issue [Board Design Frage](https://github.com/peteh/doorman/issues/17) mit @Azoninc

- TC30 KOCH ist die CH (Schweizer) version von TCS
- a (DC+) und b (DC-) sind auf 24v
- 6ms, 2ms, 4ms datenblöcke sind vorhanden
- Steuergerät ist vermutlich BVS20 

**TC30 Anschluss Platte**

Anmerkung zum Bild: bei a + b sind ein schwarzes und weisses Kabel zusätzlich angehängt - diese sind separat und gehören nicht zur TC30 installation. Sie wurden für die Nello installation verwendet.

![20240406_211514](https://github.com/peteh/doorman/assets/91615064/089a4ae7-1395-4160-ad28-923d5a8bb3cc)

**Tür Öffnungs Trigger**

![IMAGE2](https://github.com/peteh/doorman/assets/91615064/0835b05f-9cc6-4e1d-b2e9-ff929f2e0cba)

Hier noch die Schemas von TC:Bus plus Beiblatt
[Schema TC_Bus _ 1 Eingang, Anbindung an IP-Netzwerk, pot.freier Türöffnerkontakt - TC204_AVS 2100_LR12ACF.pdf](https://github.com/peteh/doorman/files/14896566/Schema.TC_Bus._.1.Eingang.Anbindung.an.IP-Netzwerk.pot.freier.Turoffnerkontakt.-.TC204_AVS.2100_LR12ACF.pdf)
[Beiblatt zu Schemas TCBus.pdf](https://github.com/peteh/doorman/files/14896567/Beiblatt.zu.Schemas.TCBus.pdf)
[Beiblatt zu Schemas TCBus.pdf](https://github.com/peteh/doorman/files/14896568/Beiblatt.zu.Schemas.TCBus.pdf)
[Schema TC_Bus _ 1 Eingang, Anbindung an IP-Netzwerk, pot.freier Türöffnerkontakt - TC204_AVS 2100_LR12ACF.pdf](https://github.com/peteh/doorman/files/14896569/Schema.TC_Bus._.1.Eingang.Anbindung.an.IP-Netzwerk.pot.freier.Turoffnerkontakt.-.TC204_AVS.2100_LR12ACF.pdf)

**Comment by peteh** [comment]
Wenn das Protokoll identisch ist koenntest du den Aufbau einfach mal dran haengen und schauen ob er was liest. 
Hier wuerde auch der Leseteil nur mit Spannungsteiler erst mal reichen.

**Comment by calibanorg** [comment]
Ich baue mal dein Teil nach gemäss deiner Doku und hänge es dran. Das Material habe ich zusammen oder bei Amazon bestellt ausser die 2x 1.2 Ohm Widerstand, der ist tricky einzeln zu finden :-) werde dann meinen Tests hier rapportieren.

**Comment by AzonInc** [comment]
Die 2x1,2 Ohm Widerstände benötigst du auch nicht. Funktioniert ohne die problemlos.

**Comment by calibanorg** [comment]
was für einen Transitor hast Du verwendet? Ich hab noch einen 740DV LM35 DZ gefunden

![image](https://github.com/peteh/doorman/assets/91615064/6cc8e9bd-6671-4afe-a2c5-ee78c362daf2)

**Comment by AzonInc** [comment]
BC517 ist das BC817 ist im Board Design.

**Comment by gee33** [comment]
Hallo zusammen, 
Ich
Lese hier seit langem mit. Die Koch Anlage ist 100% zu TCS kompatibel, bzw. Ist eigentlich nur umgelabelt. Ich habe so einen ähnlichen setup bei mir seit 3 jahren am Laufen.  Ausser dem Türöffner, da habe ich der Einfachheit halber ein relais verwendet , dass einen Tastendruck simuliert. 
Ich würde bei einer Platine aber mitmachen, dann könnte ich mein setup mal wieder modernisieren:-)
Komponenten würde ich selbst sourcen, btw. aus meinem Fundus nehmen. 
Ich habe hinter der Steckdosenkombi unter der TC50 ein unterputz  usb netzteil eingebaut. Somit brauche ich den Spannungswandler 24-3.3v nicht. 
Bin in der Schweiz.

**Comment by AzonInc** [comment]
@gee33 derzeit hatte ich geplant 5 Stück zu bestellen die alle gleich sind.
Alles was planmäßig auf dem Board nicht drauf wäre sind Schraubklemme, Pin Header und ESP.
Alle anderen SMD Teile sind bereits bei Assembly dabei da die bei allen 5 gleich sein wird.

Ich habe hier noch die v1.0 Boards liegen, da sind gar keine Teile drauf da die nur zum Test waren. Wenn du gern 0402 SMD Komponenten da drauf machen möchtest kannst du da gern eins haben. Die haben allerdings auch keine RGB LED (Nur zwei normale Status LEDs vorgesehen) und kein Relais. vorgesehen. Nur die normale Schaltung für die Bus Kommunikation. 
Dazu kommt noch dass die Traco Teile da noch eingeplant sind.

V1.0:
![image](https://github.com/peteh/doorman/assets/11911587/0c8ab7fd-cb09-45da-8f87-f82b61863d90)


Müsste man mal schauen wie man das am besten macht. Je nachdem wie viele Leute das noch haben wollen.

**Comment by peteh** [comment]
Mein Nachbar moechte seinen auch ersetzen. Also du kannst mich gern fuer 2 Boards einplanen. 
SMD Loeten wuerde ich aber gern vermeiden. THT ist kein Problem. 

- Kann man in dem Aufbau auch ueber USBC flashen oder braeuchte man einen Flasher? 
- Kannst du beim TCS Bus eventuell noch A, B und P labeln?

**Comment by AzonInc** [comment]
![image](https://github.com/peteh/doorman/assets/11911587/7adad6e6-29ba-4998-a434-ce372adbcb3b)
![image](https://github.com/peteh/doorman/assets/11911587/e7c9b85e-7dbb-41c7-bbeb-9708b5eacfa7)

So siehts insgesamt aus wenns gelifert wird.

**Comment by peteh** [comment]
Ah ok, unten sieht mans. Ich dachte nur dass es oben sinnvoller waer, weil wenn es im Case ist, sieht man die Labels nicht aber ich muss es im Case anschliessen.

**Comment by AzonInc** [comment]
Stimmt an das Case hab ich anfangs nicht gedacht da ich das Teil so in das Telefongehäuse stecken werde.
Platztechnisch passt da nicht mehr wirklich was auf die Vorderseite. Bzw. ist das ja eh alles schon so klein.
Ich könnte da noch ein + hin packen wo P ist auf der vorderseite, dann weißt du bescheid.

**Comment by peteh** [comment]
Das oder ein P vielleicht

**Comment by calibanorg** [comment]
ich hab mal mit meinem Breadboard das ganze aufgebaut gemäss @peteh wiring. was ich spezifisch ausgelassen habe sind die Button/LED wiring und die 2 1.2 Ohm Widerstände (gemäss @AzonInc brauchts die nicht). Auf P habe ich "nur" 6v gemessen sprich den D1 habe ich moment via USB direkt laufen lassen. Leider bekomme ich kein signale auf dem TC:BUS.

ist mein wiring korrekt? evtl. habe ich keine gute Verbindungen wenn ja.

![20240408_081815](https://github.com/peteh/doorman/assets/91615064/8c55273d-36ec-4825-8f3f-312a70199f9c)

**Comment by peteh** [comment]
Irgendwie fehlt ein Widerstand vom Spannungsteiler für d5 oder? Was misst du denn mit dem oszi am d5?

**Comment by gee33** [comment]
@AzonInc ich würde dann auch eine mit smd bestückte Platine nehmen. Kannst mich also fix einplanen.

**Comment by calibanorg** [comment]
> Irgendwie fehlt ein Widerstand vom Spannungsteiler für d5 oder? Was misst du denn mit dem oszi am d5?

Ja Widerstand hat gefehlt - hab das im Schema übersehen 🤦  - hab mir vermutlich grad mein wemos d1 gebraten 😞. Mit einem anderen Wemos bekomme ich die Signale wie vorgesehen. Leider habe ich gemerkt das mein ULN2003 ein APG ist nicht ein A - sprich der gibt nur 2.5 Volt aus, wenn ich das richtig gelesen habe. Muss noch warten bis ich die A version kriege das ich auch Befehle losschicken kann.

**Comment by AzonInc** [comment]
Ich glaube ich hatte auch mal so einen ULN aber in meiner Erinnerung hat das trotzdem funktioniert.

**Comment by calibanorg** [comment]
nope war nicht der Widerstand. GND hat gefehlt zum WEMOS. Als ich mich entschieden habe den Traco nicht nutzen, habe ich nicht daran gedacht GND wieder anzuschliessen. Jetzt funktionierts 🍾, ich kann alles machen :-). P habe ich nochmals gemessen beim direkten Ausgang und bekomme 22.8 Volt. Sprich meine wacklige Verkablung hat mir falsch Werte gegeben. 

@peteh &  @AzonInc  danke für die Hilfe bei debuggen

Hier noch die funktionierende Breadboard variante:
![working_prototype](https://github.com/peteh/doorman/assets/91615064/87baf8a2-ec0c-4ff7-9fe7-b3136f20b6b2)

**Comment by calibanorg** [comment]
@peteh beim kompilieren hats mir noch einen Fehler angezeigt bei main.cpp zeile 567 - 

`esp_restart()` ging nicht und ich habe es mit `system_restart();` ersetzt (wurde automatisch vorgeschlagen)

**Comment by peteh** [comment]
Ah sorry, ich hab vermutlich wieder aus Versehen ESP32 spezifischen Code ohne #ifdef rein gebaut als ich den forcierten Neustart eingebaut habe, wenn keine WiFi Verbindung zustande kommt. Ich benutze fuer meinen hier einen S3 Mini. Der passt als Drop In und hat eine nette neopixel Led. 

Beheb ich die Tage mal.

**Comment by calibanorg** [comment]
Wie schon erwähnt funktioniert mein Testaufbau. Nun wenn ich P anschliesse gemäss Schema fällt die Spannung auf 6~V runter und der TSR12450 vOut bringt noch ca 1.2v. Könnte man nicht A direct auch an TSR anschliessen? evtl noch einen Capacitor dazwischen für die Spannung zu halten - überlegung aus meinem limitierten wissen.

**Comment by AzonInc** [comment]
Was passiert denn wenn du ausschließlich den TSR anschließt ohne alles andere?

**Comment by calibanorg** [comment]
Nur B (GND) und P (20V) = 5V via TSR alles andere nicht angehängt.

**Comment by AzonInc** [comment]
Okay gut und was, wenn du mal den transistor weglässt bzw den teil allgemein zum senden von daten?

**Comment by calibanorg** [comment]
Heute nochmals getestet. TSR mit GND und P zu Vin verbunden, GND mit WEMOS D1 GND und Vout mit Wemos D1 5v verbunden. Effekt sobald ich das mache fällt die Spannung auf ca 6.3V, der Strom ist bei ca 19mA zwischen 5v und Vout.

![20240410_085148](https://github.com/peteh/doorman/assets/91615064/6107344b-0a4e-442d-9ce6-33f78fbc491d)

**Comment by calibanorg** [comment]
ich hab mal einfach so den TSR mit a (V+) und b (GND) verbunden. Das klappt ja solange die Spannung stabil bleibt. Könnte man dann nicht einem Kondensator (470uF 16V) arbeiten um die 5V stabil zu halten? ich hab mal das diagram von @peteh  genommen und angepasst - mit meinem minimalen elektrotechnischen Kenntinissen. 

![wiring_bb](https://github.com/peteh/doorman/assets/91615064/d1ae3f3c-45ae-4176-9a49-86aaab1196c2)

**Comment by calibanorg** [comment]
Meine dirty Lösung ist ein Battery Wemos Shield mit einer 1500mAH 3.7V Batterie. Nello (eine Müncher Firma die insolvenz gegangen ist) die haben auch nur a + b verwendet und dort hatten wir keine Störung mit Lautsprecher.


@peteh ich glaube das issue kann man schliessen. Ziel das es mit KOCH TC30 funktioniert ist erreicht.

**Comment by AzonInc** [comment]
Eventuell liegt es ja dann tatsächlich an dem TSR. Bleibt abzuwarten bis ich es dann mal mit dem neuen Converter testen kann.

**Comment by calibanorg** [comment]
Ich habe ein 24v Shield für WEMOS D1 (https://www.wemos.cc/en/latest/d1_mini_shield/dc_power.html) probiert. Der Effekt war der gleiche. Nello.io hat das irgendwie gelöst nur mit a + b zu verwenden ohne Störung. Leider finde ich das Gerät nicht mehr, habs vermutlich aus Wut entsorgt 🤦‍♂️, dann könnte man das PCB anschauen wie die das gelöst haben.

**Comment by AzonInc** [comment]
Im Nello ist ein Superkondensator welcher das Problem wahrscheinlich gelöst hat.

**Comment by calibanorg** [comment]
Weisst du wie gross der ist (uF)? Angehaengt vor TSR (24v) oder nach (5V)?

**Comment by AzonInc** [comment]
Gute Frage, dazu hab ich nichts weiter gefunden aber das Ding ist im Endeffekt wie ein Akku und braucht ein paar sekunden bis der aufgeladen ist. Verhältnismäßig groß von der Bauform noch dazu.

**Comment by peteh** [comment]
FYI, ein Freund von mir hat seinen alten Nello mal aufgemacht - ist aber wohl die erste HW Revision und es gab spaeter noch neuere: 

![signal-2024-04-15-165238](https://github.com/peteh/doorman/assets/918728/e9ad2422-07d0-4706-8508-58326a3e90d3)
![signal-2024-04-15-165255](https://github.com/peteh/doorman/assets/918728/a0719178-fb27-479c-8419-71caa801e282)

**Comment by peteh** [comment]
@calibanorg brauchen wir das issue noch? Die PCB Version vom doorman scheint gut zu laufen in den ersten Tests und Koch ist wohl identisch zu tcs. Dann würde ich hier zu machen

**Comment by calibanorg** [comment]
@peteh ja wir können den issue schliessen

**Comment by peteh** [comment]
Closed
