### ISSUE TITLE
No Codes :( 

### ISSUE THREAD

**Issue by alkue1** [peteh/doorman#4]
Hello,
I am enthusiastic about your project and have soldered together a board according to the instructions. Flashing the d1mini also worked without any problems. The connection to Homeassistant also works. Unfortunately, I do not get any values displayed in the TCS bus. Is it possible to narrow down the source of the error? 
I have attached a picture of the circuit board and the wall unit. 

I tried it with USB power supply, and also flashed different d1 minis. for the 147kohm I connected 100 and 47 in series.

Regards 
![20231109_211802](https://github.com/peteh/doorman/assets/109903005/3dd1e3ee-1d88-45a4-8576-d364146d8499)
![20231109_211810](https://github.com/peteh/doorman/assets/109903005/137e8255-b50f-47f9-ace0-48c267e8a4cd)
![20231109_212840](https://github.com/peteh/doorman/assets/109903005/041c1db8-f32a-4c16-9c5c-04189e4d50c0)

**Comment by peteh** [comment]
Mhm, hard to tell. Looks good from here at least. 
Are you measuring something on the D5 pin? (measure with multimeter to GND). There we should measure something around 3V. 
If you don't you could connect the P line instead of 24V+ from the bus to have a stable 24V and check again.

**Comment by alkue1** [comment]
I have since found out that there was an occasional short circuit with very low currents on the board. I was able to solve the problem with a new board.  Now I can send and receive messages with power via USB

Now, unfortunately, I have the same problem as in the closed issue, that the power supply from the Traco breaks down during the transmission process.  

I was also able to solve this problem with an external stepdown converter with two capacitors (like "DollaTek DC-DC 24V/12V to 5V"). Now I can send, but not receive 

There is now approx. 3.05V on D5 and the voltage drops when a message arrives on the bus. Is 3.05 sufficient for reception? 

I have also noticed a lot of noise in the loudspeaker when operating via P. Is there a way to avoid this? 


Many thanks for the help and the great project

**Comment by peteh** [comment]
> There is now approx. 3.05V on D5 and the voltage drops when a message arrives on the bus. Is 3.05 sufficient for reception?
> 
That sounds alright, so the led on the wemos d1 is also not blinking, e.g. when you lift up the handset? 
I just reflashed the latest master code to see if it's working in general and my led blinks when there is something on the bus, so the code should be fine. 

If you want to run further tests, just write a small program that sends something over serial when the output of digitalRead(D5) changes. Then you can see if the D5 input works in general when you lift up the handle or press the door opener button on the tcs device. 

> I have also noticed a lot of noise in the loudspeaker when operating via P. Is there a way to avoid this?
> 
For me, I haven't noticed, but I'm also running on the traco. I'm unfortunately no electric expert, my guess is that the power supply of your TCS system is not handling this well (there are only some 100mW to be drawn from the P line per device). 
> Many thanks for the help and the great project

**Comment by alkue1** [comment]
> blinking, e.g. when you lift up the handset? 

The software seems to work perfectly. The lamp now flashes briefly when sending and receiving. 

> my guess is that the power supply of your TCS system is not handling this well (there are only some 100mW to be drawn from the P line per device).

i think you are absolutely right. It seems as if the power supply breaks down for som milliseconds and forces the d1 mini to restart. I have now added a relatively large capacitor in front of the traco. At the moment everything seems to be working as it should.  :)

The last step will be a PCB so that everything fits into the existing cover in the end. 

Many thanks for the support - solved!

**Comment by peteh** [comment]
If you're making a pcb I'm very interested in having one or two as well and I'd also add the pcb files to the repo if you share them. 

I'm also interested in your capacitor solution which could maybe solve the problem of the person from the other issue. Then I could include it in general in the drawings.
